language: r
bioc_required: true
sudo: required


env:
  - global:
    - WARNINGS_ARE_ERRORS=1

before_install:

install:

script: 

on_failure:

after_failure:
  "cat /home/travis/build/arborworkflows/aRbor/aRbor.Rcheck/00install.out"

notifications:
  email:
    recipients:
      - lukeh@uidaho.edu
    on_success: change
    on_failure: change
