language: r
bioc_required: true
sudo: required


env:
  - global:
    - WARNINGS_ARE_ERRORS=1

addons:
  apt:
    packages:
      - libgsl0-dev
      - libmagick++-dev

r_github_packages:
  - uyedaj/treeplyr

after_failure:
  "cat /home/travis/build/arborworkflows/aRbor/aRbor.Rcheck/00install.out"

notifications:
  email:
    recipients:
      - lukeh@uidaho.edu
    on_success: change
    on_failure: change
